-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
SELECT * FROM gold.fact_sales
SELECT * FROM gold.dim_products
SELECT * FROM gold.fact_sales

-- Explore all countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers

-- Explore all categories 'The major divisions'
SELECT 
	DISTINCT category, 
	sub_category, 
	product_name
FROM gold.dim_products
ORDER BY 1, 2, 3

-- Find the date of the first and last order
SELECT
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date
FROM gold.fact_sales

-- How may years of sales are avaiable
SELECT
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
    MAX(EXTRACT(YEAR FROM order_date)) 
  - MIN(EXTRACT(YEAR FROM order_date)) AS years_between
FROM gold.fact_sales

-- Find the youngest and the oldest customers
SELECT
	MIN(birth_date) AS oldest_birth_date,
	EXTRACT(YEAR FROM AGE(MIN(birth_date))) AS oldest_age,
	MAX(birth_date) AS youngest_birth_date,
	EXTRACT(YEAR FROM AGE(MAX(birth_date))) AS youngest_age
FROM gold.dim_customers

-- Find the total sales
SELECT SUM(sales) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the total numbers of orders
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total numbers of products
SELECT COUNT(DISTINCT product_name) AS total_products FROM gold.dim_products

-- Find the total numbers of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers

-- Find the total numbers of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.dim_customers

-- Generate a report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, ROUND(AVG(price),2) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total no. orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total no. proucts' AS measure_name, COUNT(product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total no. customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers

-- Find the customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY 1
ORDER BY 2 DESC

-- Find the total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY 1
ORDER BY 2 DESC

-- Find the total products by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY 1
ORDER BY 2 DESC

-- Find the average costs in each category
SELECT
	category,
	AVG(product_cost) AS avg_costs
FROM gold.dim_products
GROUP BY 1
ORDER BY 2 DESC

-- Find the total_revenue generated by the category
SELECT
	P.category,
	SUM(S.sales) AS total_revneue
FROM gold.fact_sales AS S
LEFT JOIN gold.dim_products AS P USING(product_key)
GROUP BY 1
ORDER BY 2 DESC

-- What is the total revenue genreated by each customers
SELECT
	C.customer_key,
	CONCAT(C.first_name,' ',C.last_name) AS customer_name,
	SUM(S.sales) AS total_revenue
FROM gold.fact_sales AS S
LEFT JOIN gold.dim_customers AS C 
ON S.customer_key = C.customer_key
GROUP BY 1, 2
ORDER BY 3 DESC

-- What is ths distribution of sold items aross countries
SELECT
	C.country,
	SUM(S.quantity) AS total_sold_items
FROM gold.fact_sales AS S
LEFT JOIN gold.dim_customers AS C
ON C.customer_key = S.customer_key
GROUP BY 1
ORDER BY 2 DESC
	
-- Which 5 products generate the highest revenue
SELECT
	P.product_name,
	SUM(S.sales) AS total_revenue
FROM gold.fact_sales AS S
LEFT JOIN gold.dim_products AS P 
ON P.product_key = S.product_key
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5

-- Which are the 5 worst-performinig products in terms of sales
SELECT
	P.product_name,
	SUM(S.sales) AS total_revenue
FROM gold.fact_sales AS S
LEFT JOIN gold.dim_products AS P 
ON P.product_key = S.product_key
GROUP BY 1
ORDER BY 2 ASC
LIMIT 5

-- find the top 10 customers whow have generated the highest revenue
SELECT *
FROM(SELECT
		C.customer_key,
		CONCAT(C.first_name,' ',C.last_name) AS customer_name,
		COALESCE(SUM(S.sales),0)  AS total_revneue,
		DENSE_RANK()
			OVER(ORDER BY COALESCE(SUM(S.sales),0) DESC) AS rnk
	FROM gold.dim_customers AS C
	LEFT JOIN gold.fact_sales AS S
	ON C.customer_key = S.customer_key
	GROUP BY 1, 2) AS X
WHERE X.rnk <= 10
